std_msgs/Header header 
#  [] [0|1]
bool allow_self_driving_run 
#  [] [0|7]
int32 vcu_chassis_estop_sta_fb 
#  [] [0|0]
bool clearance_lamp_actual 
#  [] [0|0]
int32 car_work_state 
#  [] [0|0]
int32 car_power_state 
#  [] [0|0]
bool aeb_trigger_state 
#  [] [0|1]
bool brake_light_actual 
#  [] [0|0]
bool headlight_actual 
#  [] [0|0]
int32 turn_light_actual 
#  [] [0|255]
int32 vehicle_errcode 
#  [] [0|7]
int32 drive_mode_status 
#  [] [0|7]
int32 steer_mode_status 
#  [] [0|0]
int32 vehicle_mode_state 
#  [] [0|0]
bool vehicle_front_crash_state 
#  [] [0|0]
bool back_crash_state 
#  [] [0|0]
bool aeb_state 
#  [m/s^2] [-10|10]
float32 vehicle_acc 
#  [m/s] [-32.768|32.767]
float32 vehicle_speed 
