std_msgs/Header header 
#  [] [0|0]
bool auto_prompts 
#  [] [0|0]
bool clearance_lamp_ctrl 
#  [] [0|0]
bool turn_right_prompts 
#  [] [0|0]
bool turn_left_prompts 
#  [] [0|0]
bool headlight_ctrl 
#  [] [0|0]
bool back_up_prompts 
#  [] [0|0]
int32 vehicle_door_ctrl 
#  [] [0|255]
int32 check_sum105 
#  [] [0|7]
int32 turn_light_ctrl 
#  [] [0|1]
bool vehicle_vin_req 
#  [] [0|7]
int32 drive_mode_ctrl 
#  [] [0|7]
int32 steer_mode_ctrl 
