std_msgs/Header header 
# 位置灯控制 [] [0|1]
int8 acu_vehicle_pos_lamp_ctrl 
# 近光灯控制 [] [0|1]
int8 acu_vehicle_head_lamp_ctrl 
# 左转向灯控制 [] [0|1]
int8 acu_vehicle_left_lamp_ctrl 
# 右转向灯控制 [] [0|1]
int8 acu_vehicle_right_lamp_ctrl 
# 远光灯控制 [] [0|1]
int8 acu_vehicl_high_beam_ctrl 
# 雾灯控制 [] [0|1]
int8 acu_vehicle_fog_lamp_ctrl 
# 氛围灯控制 [] [0|1]
int8 acu_vehicle_body_light_crtl 
# 车内灯光总控制 [] [0|1]
int8 acu_vehicle_read_light_crtl 
# 提示音控制 [] [0|3]
int8 acu_vehicle_voice 
# 雨刮控制 [] [0|3]
int8 acu_vehicle_wipers_crtl 
# 车门控制 [] [0|3]
int8 acu_vehicle_door_crtl 
# 车窗控制（预留） [] [0|7]
int8 acu_vehicle_window_crtl 
# 限速控制 [] [0|1]
int8 acu_chassis_speed_limite_mode 
# 速度限制值 [m/s] [5|20]
int32 acu_chassis_speed_limite_val 
# 校验模式使能(预留) [] [0|1]
int8 acu_check_sum_en 
