std_msgs/Header header 
# 电机系统过温 [] [0|1]
int8 vcu_sys_motor_over_temp_sta 
# 电池系统过温 [] [0|1]
int8 vcu_sys_bms_over_temp_sta 
# 制动系统过温 [] [0|1]
int8 vcu_sys_brake_over_temp_sta 
# 转向系统过温 [] [0|1]
int8 vcu_sys_steer_over_temp_sta 
# 蓄电池电压过低 [] [0|1]
int8 vcu_sys_under_volt 
# 系统故障 [] [0|15]
int8 vcu_sys_flt 
# 制动系统故障 [] [0|15]
int8 vcu_sys_brake_flt 
# 驻车系统故障 [] [0|15]
int8 vcu_sys_parking_flt 
# 前转向系统故障 [] [0|15]
int8 vcu_sys_steer_front_flt 
# 后转向系统故障 [] [0|15]
int8 vcu_sys_steer_back_flt 
# 左前电机系统故障 [] [0|15]
int8 vcu_sys_motor_lf_flt 
# 右前电机系统故障 [] [0|15]
int8 vcu_sys_motor_rf_flt 
# 左后电机系统故障 [] [0|15]
int8 vcu_sys_motor_lr_flt 
# 右后电机系统故障 [] [0|15]
int8 vcu_sys_motor_rr_flt 
# BMS系统故障 [] [0|15]
int8 vcu_sys_bms_flt 
# DC系统故障 [] [0|15]
int8 vcu_sys_dc_flt 
