std_msgs/Header header 
#  [rpm] [0|65535]
int32 fan_speed_ctrl 
#  [] [0|3]
int32 mowing_speed_ctrl 
#  [] [0|3]
int32 sweep_mode_ctrl 
#  [] [0|1]
bool fan_speed_mode 
#  [] [0|3]
int32 fan_mode_ctrl 
#  [] [0|3]
int32 sweep_plate_up_down 
#  [] [0|3]
int32 mouthpiece_up_down_ctrl 
#  [] [0|1]
bool shaker_duster_ctrl 
#  [] [0|1]
bool dedusting_ctrl 
#  [] [0|3]
int32 auto_garbage_dump_start_ctrl 
#  [] [0|3]
int32 auto_cleaning_start_ctrl 
