std_msgs/Header header 
#  [rpm] [0|65535]
int32 scu_mowing_speed_fb 
#  [] [0|3]
int32 push_rod_travel_difference_alarm 
#  [] [0|1]
bool end_of_garbage_dumping_des 
#  [] [0|1]
bool end_of_garbage_dumping 
#  [rpm] [0|65535]
int32 scu_fan_speed_fb 
#  [] [0|255]
int32 scu_liquid_leve 
#  [] [0|1]
bool s_c_u__heartbeat 
#  [] [0|1]
bool scan_controller_communication_fault 
#  [] [0|1]
bool fan_controller_communication_fault 
#  [] [0|1]
bool s_c_u__filter_clogging 
#  [] [0|1]
bool s_c_u__sweep_life_end 
#  [] [0|1]
bool s_c_u__dustbin_full 
#  [] [0|1]
bool scu_liquid_leve_high 
#  [] [0|1]
bool scu_liquid_level_low 
