std_msgs/Header header 
#  [] [0|255]
int32 chassis_rr_eds_error_code2 
#  [] [0|255]
int32 chassis_rf_eds_error_code2 
#  [] [0|255]
int32 chassis_lr_eds_error_code2 
#  [] [0|255]
int32 chassis_lf_eds_error_code2 
#  [] [0|255]
int32 chassis_rr_eds_error_code 
#  [] [0|255]
int32 chassis_rf_eds_error_code 
#  [] [0|255]
int32 chassis_lr_eds_error_code 
#  [] [0|255]
int32 chassis_lf_eds_error_code 
