std_msgs/Header header 
#  [] [0|1]
bool bms_communication_fault 
#  [] [0|1]
bool chassis_emergency_sta 
#  [] [0|1]
bool leadacid_battery_low 
#  [] [0|1]
bool controler_communication_fault 
#  [] [0|1]
bool chassis_crash_sta 
#  [] [0|1]
bool eps_rear_communication_fault 
#  [] [0|1]
bool eps_front_communication_fault 
#  [] [0|1]
bool eds_rr_communication_fault 
#  [] [0|1]
bool eds_rf_communication_fault 
#  [] [0|1]
bool eds_lr_communication_fault 
#  [] [0|1]
bool eds_lf_communication_fault 
#  [] [0|1]
bool ebs_communication_fault 
#  [] [0|255]
int32 chassis_vcu_other_err 
#  [] [0|17]
int32 bms_fault1 
#  [] [0|17]
int32 bms_fault2 
#  [] [0|17]
int32 bms_fault3 
#  [] [0|17]
int32 bms_fault4 
#  [] [0|17]
int32 bms_fault5 
#  [] [0|17]
int32 bms_fault6 
#  [] [0|17]
int32 bms_fault7 
#  [] [0|17]
int32 bms_fault8 
#  [] [0|17]
int32 bms_fault9 
#  [] [0|17]
int32 bms_fault10 
#  [] [0|17]
int32 bms_fault11 
#  [] [0|17]
int32 bms_fault12 
#  [] [0|17]
int32 bms_fault13 
