std_msgs/Header header 
#  [] [0|3]
int32 turn_light_actual 
#  [] [0|1]
bool aeb_trigger_state 
#  [] [0|1]
bool headlight_actual 
#  [] [0|7]
int32 car_work_state 
#  [] [0|1]
int32 car_power_state 
#  [] [0|255]
int32 vehicle_errcode 
#  [] [0|1]
bool aeb_brake_state 
#  [] [0|1]
bool front_crash_state 
#  [] [0|1]
bool back_crash_state 
#  [] [0|3]
int32 vehicle_mode_state 
#  [] [0|7]
int32 drive_mode_status 
#  [m/s] [-32.768|32.767]
float32 vehicle_speed 
#  [] [0|7]
int32 steer_mode_status 
#  [] [0|1]
bool brake_light_actual 
#  [m/s^2] [-10|10]
float32 vehicle_acc 
