Header header 
#  [] [0|255]
int32 EBS_MotAglFbk 
#  [] [0|1]
bool EBS_WarningLight 
#  [] [0|14]
int32 EBS_StMode 
#  [] [0|125]
int32 EBS_PresFbk 
#  [] [0|65535]
int32 EBS_Fault_Info 
#  [] [0|1]
bool EBS_ExtBrkPrio 
#  [] [0|1]
bool EBS_DrvrInteraction 
#  [] [0|15]
int32 EBS_ctRoll 
#  [] [0|1]
bool EBS_BrkPedalApplied_V 
#  [] [0|1]
bool EBS_BrkPedalApplied 
#  [] [0|1]
bool EBS_Brakelight 
